[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM3
monitor_port = COM3

lib_deps =
    adafruit/adafruit SSD1306
    adafruit/adafruit GFX Library
    adafruit/adafruit PN532@^1.3.0